Repository Wordcab/wordcab-transcribe, pull requests merged in 2023-08, with the labels that each got.

#179 Fix lack of word scores in stereo, prompt issues
  wordcab_transcribe/services/transcribe_service.py
Labels: bug, transcription, diarization

#180 Split NeMo diarization process into sub-modules
  .env
  .gitignore
  Dockerfile
  config/nemo/diar_infer_general.yaml
  config/nemo/diar_infer_meeting.yaml
  config/nemo/diar_infer_telephonic.yaml
  split_diarization.ipynb
  tests/test_config.py
  tests/utils/test_load_nemo_config.py
  wordcab_transcribe/config.py
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/diarize_service.py
  wordcab_transcribe/services/post_processing_service.py
  wordcab_transcribe/services/transcribe_service.py
  wordcab_transcribe/utils.py
Labels: api, diarization

#183 Updated license info in all modules
  wordcab_transcribe/__init__.py
  wordcab_transcribe/config.py
  wordcab_transcribe/dependencies.py
  wordcab_transcribe/logging.py
  wordcab_transcribe/main.py
  wordcab_transcribe/models.py
  wordcab_transcribe/router/__init__.py
  wordcab_transcribe/router/authentication.py
  wordcab_transcribe/router/v1/__init__.py
  wordcab_transcribe/router/v1/audio_file_endpoint.py
  wordcab_transcribe/router/v1/audio_url_endpoint.py
  wordcab_transcribe/router/v1/cortex_endpoint.py
  wordcab_transcribe/router/v1/endpoints.py
  wordcab_transcribe/router/v1/live_endpoints.py
  wordcab_transcribe/router/v1/youtube_endpoint.py
  wordcab_transcribe/services/__init__.py
  wordcab_transcribe/services/align_service.py
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/diarize_service.py
  wordcab_transcribe/services/gpu_service.py
  wordcab_transcribe/services/post_processing_service.py
  wordcab_transcribe/services/transcribe_service.py
  wordcab_transcribe/services/vad_service.py
  wordcab_transcribe/utils.py
Labels: documentation

#184 Prepare v0.4.0 release
  .env
  .gitattributes
  README.md
  notebooks/.gitkeep
  notebooks/async_inference.py
  notebooks/local_audio_inference.py
  notebooks/split_diarization.ipynb
  notebooks/youtube_inference.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/test_batch_request.py
  tests/test_config.py
  tests/test_important_files.py
  tests/test_models.py
  tests/utils/__init__.py
  tests/utils/test_convert_functions.py
  tests/utils/test_delete_file.py
  tests/utils/test_format_punct.py
  tests/utils/test_get_segment_timestamp_anchor.py
  tests/utils/test_is_empty_string.py
  tests/utils/test_retrieve_user_platform.py
  wordcab_transcribe/config.py
Labels: documentation

#188 Update API models
  .pre-commit-config.yaml
  notebooks/async_inference.py
  notebooks/local_audio_inference.py
  notebooks/youtube_inference.py
  tests/test_models.py
  wordcab_transcribe/models.py
Labels: enhancement, api

#186 Find a solution to avoid CUDA OOM during diarization
  .flake8
  .github/workflows/quality.yml
  notebooks/dev_timeit.ipynb
  notebooks/youtube_inference.py
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/diarization/__init__.py
  wordcab_transcribe/services/diarization/clustering_module.py
  wordcab_transcribe/services/diarization/diarize_service.py
  wordcab_transcribe/services/diarization/models.py
  wordcab_transcribe/services/diarization/segmentation_module.py
  wordcab_transcribe/services/diarization/utils.py
  wordcab_transcribe/services/diarize_service.py
Labels: bug, diarization

#195 194 add option to change oracle num speakers parameter
  README.md
  notebooks/async_inference.py
  notebooks/local_audio_inference.py
  notebooks/youtube_inference.py
  tests/test_models.py
  wordcab_transcribe/models.py
  wordcab_transcribe/router/v1/audio_file_endpoint.py
  wordcab_transcribe/router/v1/audio_url_endpoint.py
  wordcab_transcribe/router/v1/cortex_endpoint.py
  wordcab_transcribe/router/v1/youtube_endpoint.py
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/diarization/clustering_module.py
  wordcab_transcribe/services/diarization/diarize_service.py
Labels: api, diarization

#198 Update poetry dependencies to enable repetition_penalty updates
  poetry.lock
Labels: enhancement, transcription, deploy

#200 Update poetry dependencies to fix repetition_penalty update
  poetry.lock
Labels: bug, transcription

#201 Add `inference_warmup`
  wordcab_transcribe/assets/warmup_sample.wav
  wordcab_transcribe/main.py
  wordcab_transcribe/services/asr_service.py
Labels: api

#204 Make repetition penalty an adjustable parameter
  notebooks/local_audio_inference.py
  poetry.lock
  pyproject.toml
  tests/test_models.py
  wordcab_transcribe/models.py
  wordcab_transcribe/router/v1/audio_file_endpoint.py
  wordcab_transcribe/router/v1/audio_url_endpoint.py
  wordcab_transcribe/router/v1/cortex_endpoint.py
  wordcab_transcribe/router/v1/youtube_endpoint.py
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/transcribe_service.py
Labels: api, transcription

#209 Add `bfloat16` to compute types
  .env
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_batch_request.py
  wordcab_transcribe/config.py
Labels: api, transcription

#213 Update the api
  Dockerfile
  notebooks/async_inference.py
  notebooks/youtube_inference.py
  noxfile.py
  tests/test_models.py
  wordcab_transcribe/config.py
  wordcab_transcribe/dependencies.py
  wordcab_transcribe/logging.py
  wordcab_transcribe/main.py
  wordcab_transcribe/models.py
  wordcab_transcribe/router/v1/audio_file_endpoint.py
  wordcab_transcribe/router/v1/audio_url_endpoint.py
  wordcab_transcribe/router/v1/cortex_endpoint.py
  wordcab_transcribe/router/v1/youtube_endpoint.py
  wordcab_transcribe/services/align_service.py
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/transcribe_service.py
  wordcab_transcribe/utils.py
Labels: api, transcription

#218 Fix tests
  tests/test_models.py
  wordcab_transcribe/assets/mel_filters.npz
  wordcab_transcribe/config.py
  wordcab_transcribe/dependencies.py
  wordcab_transcribe/main.py
  wordcab_transcribe/router/v1/audio_file_endpoint.py
  wordcab_transcribe/router/v1/audio_url_endpoint.py
  wordcab_transcribe/router/v1/youtube_endpoint.py
  wordcab_transcribe/services/align_service.py
Labels: bug

#220 Optimizing dual-channel pipeline
  wordcab_transcribe/services/post_processing_service.py
  wordcab_transcribe/services/transcribe_service.py
Labels: enhancement, transcription, diarization

#94 Add utils function to run an api call for each endpoint #23
  wordcab_transcribe/automate.py
Labels: enhancement, api

#223 Add empty audio catch
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/diarization/diarize_service.py
  wordcab_transcribe/utils.py
Labels: api, diarization

#202 Re-implement EncDecSpeakerLabelModel
  .pre-commit-config.yaml
  Dockerfile
  notebooks/implement_segmentation.ipynb
  notebooks/youtube_inference.py
  noxfile.py
  poetry.lock
  pyproject.toml
  wordcab_transcribe/config.py
  wordcab_transcribe/services/diarization/models.py
  wordcab_transcribe/services/diarization/modules.py
  wordcab_transcribe/services/diarization/segmentation_module.py
  wordcab_transcribe/services/diarization/utils.py
  wordcab_transcribe/utils.py
Labels: diarization, deploy
