Repository Wordcab/wordcab-transcribe, pull requests merged in 2023-10, with the labels that each got.

#261 Implement `only_transcription` and `only_diarization`
  .env
  notebooks/audio_url_inference.py
  notebooks/transcribe_endpoint_only.py
  pyproject.toml
  src/wordcab_transcribe/config.py
  src/wordcab_transcribe/dependencies.py
  src/wordcab_transcribe/logging.py
  src/wordcab_transcribe/models.py
  src/wordcab_transcribe/pydantic_annotations.py
  src/wordcab_transcribe/router/v1/diarize_endpoint.py
  src/wordcab_transcribe/router/v1/endpoints.py
  src/wordcab_transcribe/router/v1/transcribe_endpoint.py
  src/wordcab_transcribe/services/asr_service.py
  src/wordcab_transcribe/services/diarization/diarize_service.py
  src/wordcab_transcribe/services/post_processing_service.py
  src/wordcab_transcribe/services/transcribe_service.py
  src/wordcab_transcribe/utils.py
  tests/test_config.py
  tests/test_models.py
Labels: api, transcription, diarization

#268 Fix `dual_channel` bug
  src/wordcab_transcribe/models.py
  src/wordcab_transcribe/services/post_processing_service.py
  src/wordcab_transcribe/services/transcribe_service.py
Labels: bug

#266 Update switch between local and remote and reverse
  src/wordcab_transcribe/services/asr_service.py
Labels: api, deploy

#273 Fix bug with empty utterances
  src/wordcab_transcribe/services/post_processing_service.py
Labels: bug

#269 Add documentation
  .github/workflows/quality.yml
  docs/contributing.md
  docs/index.md
  docs/license.md
  docs/reference/config.md
  docs/reference/schemas.md
  docs/reference/services.md
  docs/usage/asr.md
  docs/usage/env.md
  docs/usage/launch.md
  mkdocs.yml
  pyproject.toml
Labels: documentation

#271 Adjust VAD speech padding for diarizer, add additional logic to speak…
  src/wordcab_transcribe/services/post_processing_service.py
  src/wordcab_transcribe/services/vad_service.py
Labels: diarization

#276 Release v0.5.2
  README.md
  src/wordcab_transcribe/__init__.py
Labels: documentation
