Repository Wordcab/wordcab-transcribe, pull requests merged in 2023-07, with the labels that each got.

#136 New post-processing strategy
  tests/utils/test_load_nemo_config.py
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/post_processing_service.py
Labels: api, transcription, diarization

#138 add gpu index logging
  wordcab_transcribe/services/asr_service.py
Labels: deploy

#140 fix diarization gpu usage
  wordcab_transcribe/services/diarize_service.py
Labels: bug, diarization

#144 Send svix identifiers only, while full payload ends up in S3
  wordcab_transcribe/router/v1/cortex_endpoint.py
Labels: api

#142 Adding internal_vad parameter which seems to fix output with empty utterances
  tests/test_models.py
  wordcab_transcribe/models.py
  wordcab_transcribe/router/v1/audio_file_endpoint.py
  wordcab_transcribe/router/v1/audio_url_endpoint.py
  wordcab_transcribe/router/v1/cortex_endpoint.py
  wordcab_transcribe/router/v1/youtube_endpoint.py
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/transcribe_service.py
Labels: bug, transcription

#146 Add nginx conf for custom deploy
  README.md
  nginx.conf
Labels: deploy

#152 Fix dual_channel word timestamps
  wordcab_transcribe/services/asr_service.py
  wordcab_transcribe/services/post_processing_service.py
  wordcab_transcribe/services/transcribe_service.py
Labels: bug

#160 Enabling alignment so users can toggle
  wordcab_transcribe/services/asr_service.py
Labels: enhancement, transcription, diarization

#162 defaulting to original Whisper timestamps if alignment returns None for start, end, or score
  wordcab_transcribe/services/align_service.py
Labels: bug

#164 Adding more alignment models for cs, in, sl, and th
  wordcab_transcribe/services/align_service.py
Labels: enhancement, transcription, diarization

#168 Add a download queue
  wordcab_transcribe/dependencies.py
  wordcab_transcribe/router/v1/audio_url_endpoint.py
  wordcab_transcribe/router/v1/youtube_endpoint.py
  wordcab_transcribe/utils.py
Labels: api, deploy

#170 Setting prompt="" instead of None, as None causes empty output for some presigned URLs
  wordcab_transcribe/services/transcribe_service.py
Labels: bug

#171 Revert "Setting prompt="" instead of None
  wordcab_transcribe/services/transcribe_service.py
Labels: bug
