Repository Wordcab/wordcab-transcribe, pull requests merged in 2023-04, with the labels that each got.

#2 Improve tests
  .coverage
  .github/workflows/quality.yml
  .gitignore
  README.md
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/sample_1.mp3
  tests/test_batch_request.py
  tests/test_config.py
  tests/test_models.py
Labels: enhancement

#5 fix hms ms dot
  wordcab_transcribe/utils.py
Labels: bug

#10 add release workflow + tools
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: documentation

#18 Adding audio-url endpoint for presigned URLs and fixed single-speaker…
  .coverage
  poetry.lock
  pyproject.toml
  requirements.txt
  wordcab_transcribe/main.py
  wordcab_transcribe/service.py
  wordcab_transcribe/utils.py
Labels: bug, enhancement

#25 Quality improvements + input models
  .env
  README.md
  poetry.lock
  pyproject.toml
  tests/test_config.py
  tests/test_models.py
  wordcab_transcribe/main.py
  wordcab_transcribe/models.py
  wordcab_transcribe/service.py
Labels: bug, enhancement

#26 Move requirements.txt copy command below package installs
  Dockerfile
Labels: enhancement
